### ISSUE TITLE
Bug: HTML comments in text break image insertion

### ISSUE THREAD

**Issue by aprudnikoff** [tinymce/tinymce#3826]
Here's [fiddle](http://fiddle.tinymce.com/QVfaab)

**Steps to reproduce:**
1. Leave caret at the beginning of the text.
2. Click "Insert/Edit image".
3. Insert any image url.
4. Click "Ok".

**Actual result:**
Console error and nothing happens
tinymce.js:21146 Uncaught DOMException: Failed to execute 'insertNode' on 'Range': The node to be inserted contains a 'IMG' node, which may not be inserted here.
    at Selection.setContent (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:21146:21)
    at http://fiddle.tinymce.com/tinymce/4.6.4/plugins/image/plugin.js:405:32
    at Object.ignore (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:25782:13)
    at Object.transact (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:25766:16)
    at Class.onSubmitForm (http://fiddle.tinymce.com/tinymce/4.6.4/plugins/image/plugin.js:387:30)
    at Dispatcher.fire (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:30842:31)
    at Class.fire (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:33268:41)
    at Class.fire (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:33274:20)
    at Class.submit (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:50815:21)
    at Class.onclick (http://fiddle.tinymce.com/tinymce/4.6.4/tinymce.js:36937:37)

**Some notes:**
1. If you move caret from the beginning to some other location — it works.
2. If you remove HTML comment — it works.
3. If you move HTML comment outside of surrounding div — it works.

Finally, I haven't found any way to clean up HTML comments on initialization and during editing.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
