### ISSUE TITLE
Fullscreen plugin throws an error in inline mode

### ISSUE THREAD

**Issue by mbaneryd** [tinymce/tinymce#4186]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The fullscreen plugin throws an "Uncaught TypeError: Cannot read property 'style' of null" exception when used on an inline editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/pjgaab/1

```
<script type="text/javascript">
tinymce.init({
    selector: "#content",
	inline: true,
    plugins: [
        "fullscreen"
    ],
    toolbar: "fullscreen"
});
</script>

<div id="content">Yo</div>
```
Click on the fullscreen menu item.  The following error will occur in the console
```
plugin.js:84 Uncaught TypeError: Cannot read property 'style' of null
    at Object.toggleFullscreen (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/plugins/fullscreen/plugin.js:84:44)
    at Editor.<anonymous> (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/plugins/fullscreen/plugin.js:130:26)
    at commands.exec.(anonymous function) (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:13194:25)
    at EditorCommands.execCommand (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:13110:9)
    at Editor.execCommand (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:24017:34)
    at Class.settings.onclick (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:23962:16)
    at Dispatcher.fire (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:13572:29)
    at Class.fire (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/themes/modern/theme.js:2497:39)
    at HTMLDivElement.delegate (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/themes/modern/theme.js:2818:17)
    at executeHandlers (http://fiddle-cdn.azureedge.net/tinymce/4.7.6/tinymce.js:971:41)
toggleFullscreen @ plugin.js:84
(anonymous) @ plugin.js:130
commands.exec.(anonymous function) @ tinymce.js:13194
execCommand @ tinymce.js:13110
execCommand @ tinymce.js:24017
settings.onclick @ tinymce.js:23962
fire @ tinymce.js:13572
fire @ theme.js:2497
delegate @ theme.js:2818
executeHandlers @ tinymce.js:971
defaultNativeHandler @ tinymce.js:984
```

**What is the expected behavior?**
It should not add the menu item if the editor is configured as an inline editor. Or at least it should not throw an exception.

I know that the plugin is not designed to work in inline mode but we allow other developers to configure which plugins that should be used inside the editor, and it would be hard for all of the to know that the fullscreen plugin can't be used in all modes. So from a developer perspective it would be better if the plugin itself would not add the buttons if it does not support the current mode. (as it did before)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.6

This worked in earlier versions, the inline check was removed when the plugin was separated into several modules.

https://github.com/tinymce/tinymce/commit/5e5926741f204b002029185d24d930820f6ebe51#diff-bd5320757d8a2d4d6a963491699e9127L32

**Comment by fyrkant** [comment]
This has been fixed in 4.7.7 released today.

Closing this issue but if you can reproduce it in 4.7.7 leave a comment and I can open it up again.
