### ISSUE TITLE
Invalid IIFE Structure break webpack bundle

### ISSUE THREAD

**Issue by vincent-cm** [tinymce/tinymce#4507]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Error during output bundle file:

ERROR in ./src/assets/tinymce/tinymce.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Invalid IIFE Structure
    at updateEnumIife (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:307:15)
    at visitBlockStatements (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:82:61)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:33:26)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at visitFunctionBody (/node_modules/typescript/lib/typescript.js:56942:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57062:407)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57052:44)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57060:45)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57106:49)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at Object.visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at visitBlockStatements (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:121:27)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:33:26)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at visitFunctionBody (/node_modules/typescript/lib/typescript.js:56942:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57062:407)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57060:45)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57052:44)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/node_modules/typescript/lib/typescript.js:57106:49)
    at visitor (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at Object.visitNode (/node_modules/typescript/lib/typescript.js:56836:23)
    at visitBlockStatements (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:121:27)
    at transformer (/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:21:28)
    at /node_modules/typescript/lib/typescript.js:3073:46
 @ ./src/app/plugins/tinyMce.ts 2:0-38
 @ ./src/app/modules/template/prepare/prepare.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Install ng-cli
create a sample angular2 app
import tinymce into the app:

import "./tinymce/tinymce";

Use tinymce to activate a tinymce textarea:
tinymce.init({});

**What is the expected behavior?**
Build success same to tinymce <= 4.7.4
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

> 4.7.4 now I am using 4.8.1

Related to 
https://github.com/tinymce/tinymce/issues/4165
https://github.com/angular/angular-cli/issues/11041

**Comment by Afraithe** [comment]
We highly suggest you use the packs made for this type of integration.

https://github.com/tinymce/tinymce-angular

**Comment by fyrkant** [comment]
Try importing the minified file instead, does that work?

**Comment by isawk** [comment]
work around in angular 6 

angular.json
scripts include "node_modules/tinymce/tinymce.min.js"

in component, declare tinymce
declare var tinymce:any;
