### ISSUE TITLE
Link plugin cause jawr to crash

### ISSUE THREAD

**Issue by Cousin-Hub** [tinymce/tinymce#5318]
Tested with tinymce version 5.1.3 and 5.1.4
JAWR 3.9
JAWR crashes on launch :

SEVERE [main] org.apache.catalina.core.StandardContext.loadOnStartup Le Servlet [JavascriptServlet] dans l'application web [] a retourné une exception lors de son chargement
 net.jawr.web.minification.JSMin$UnterminatedRegExpLiteralException
	at net.jawr.web.minification.JSMin.action(JSMin.java:277)
	at net.jawr.web.minification.JSMin.jsmin(JSMin.java:378)
	at net.jawr.web.resource.bundle.postprocess.impl.JSMinPostProcessor.doPostProcessBundle(JSMinPostProcessor.java:78)
	at net.jawr.web.resource.bundle.postprocess.impl.AbstractJsChainedResourceBundlePostProcessor.postProcessBundle(AbstractJsChainedResourceBundlePostProcessor.java:58)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.executeBundlePostProcessing(ResourceBundlesHandlerImpl.java:1449)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.joinAndPostprocessBundle(ResourceBundlesHandlerImpl.java:1387)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.joinAndPostProcessBundle(ResourceBundlesHandlerImpl.java:1300)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.joinAndStoreBundle(ResourceBundlesHandlerImpl.java:1238)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.build(ResourceBundlesHandlerImpl.java:863)
	at net.jawr.web.resource.bundle.handler.ResourceBundlesHandlerImpl.initAllBundles(ResourceBundlesHandlerImpl.java:703)
	at net.jawr.web.resource.bundle.factory.BundlesHandlerFactory.buildResourceBundlesHandler(BundlesHandlerFactory.java:286)
	at net.jawr.web.resource.bundle.factory.PropertiesBasedBundlesHandlerFactory.buildResourceBundlesHandler(PropertiesBasedBundlesHandlerFactory.java:198)
	at net.jawr.web.servlet.JawrRequestHandler.initializeJawrConfig(JawrRequestHandler.java:536)
	at net.jawr.web.servlet.JawrRequestHandler.initializeJawrContext(JawrRequestHandler.java:342)
	at net.jawr.web.servlet.JawrRequestHandler.initRequestHandler(JawrRequestHandler.java:291)
	at net.jawr.web.servlet.JawrRequestHandler.<init>(JawrRequestHandler.java:217)
	at net.jawr.web.servlet.JawrServlet.init(JawrServlet.java:64)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1123)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1078)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:971)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4868)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5184)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:928)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:634)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)

If I use file plugin.js rename as plugin.min.js, no problem
If I recompress the file plugin.js  with https://javascript-minifier.com/, the file is slightly bigger than original but does not causes crash

**Comment by lnewson** [comment]
I checked both the minified code and the regular code for unterminated regexes and they are all the same (see below). As such this seems like it's a bug with JAWR, so I'd recommend logging an issue against the JAWR project. It's also worth noting that if you are using JAWR, based on it's description you shouldn't be using the minified files anyways, as it handles minification as well.

| plugin.js | plugin.min.js |
| ----------- | ----------------- |
| `/^\w+:/i` | `/^\w+:/i` |
| `/\s+/` | `/\s+/` |
| `/\bimage\b/i` | `/\bimage\b/i` |
| `/</` | `/</` |
| `/^<a [^>]+>[^<]+<\/a>$/` | `/^<a [^>]+>[^<]+<\/a>$/` |
| `/\uFEFF/` | `/\uFEFF/g` |
| `/^#/` | `/^#/` |
| `/^\s*www[\.\|\d\.]/i` | `/^\s*www[\.\|\d\.]/i` |

As a side note we use UglifyJS to do our minification, so it's possible there's something JAWR's doesn't like about how UglifyJS does it's minification. However since it's valid JS, the bug still seems to be most likely in JAWR.
