### ISSUE TITLE
Failed to execute 'setStart' on 'Range': There is no child at offset <x>.

### ISSUE THREAD

**Issue by anormal81** [tinymce/tinymce#7406]
Using tinymce (e.g. Version 5.10.2) with following settings:

HTML:
`<textarea></textarea>`

Javascript:
```
tinymce.init({
	selector: 'textarea',
	forced_root_block: 'div'
});
```

https://fiddle.tiny.cloud/cRhaab/1

Now type 'a' -> Shift+Enter -> 'b' -> Backspace to delete the 'b'.
Now there is an error in the console:
```
Uncaught DOMException: Failed to execute 'setStart' on 'Range': There is no child at offset 2.
    at N0 (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:293958)
    at _x.<anonymous> (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:2053)
    at rx.fire (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:357993)
    at _x.fire (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:361357)
    at t1.nodeChanged (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:314734)
    at _x.nodeChanged (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:367306)
    at _x.<anonymous> (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:315608)
    at rx.fire (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:357993)
    at _x.fire (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:361357)
    at ax (https://cdn.tiny.cloud/1/pdotdn6ajz23g86qg3ra8vbddxap1vl6k4h6rvyf51ye7ef9/tinymce/5-stable/tinymce.min.js:4:360131)
```

Our software uses version Version 5.6.1.
Reproducible in the fiddle with latest stable of version 5

It is a huge impact for our customers. Please provide a fix in version 5. Thanks

**Comment by sophiekoonin** [comment]
We're having the same problem when you backspace with cmd+backspace.  It seems to still work, it's just throwing an error in the console.

**Comment by elirov** [comment]
Same issue.

**Comment by jasperf** [comment]
@anormal81 did you every resolve this issue on execution of `setStart` on `Range`?

**Comment by anormal81** [comment]
> @anormal81 did you every resolve this issue on execution of `setStart` on `Range`?

@jasperf Unfortunately there is no fix here yet

**Comment by jasperf** [comment]
Said to see this issue still has no solution after all this time. Just commented linked thread to keep this issue alive . Leaving note here hoping someone who has come up with solution reads this and shares this here.

**Comment by spocke** [comment]
I'm happy to report that a fix for this has been merged https://github.com/tinymce/tinymce/pull/9621 we haven't released it yet.

**Comment by jasperf** [comment]
@spocke that is great news! Looking forward to be able to deal with this issue in new release!
