### ISSUE TITLE
why？？？ vue 2x

### ISSUE THREAD

**Issue by shwanduan** [tinymce/tinymce#8025]
Cannot read properties of undefined (reading 'scroll')

**Comment by jg-8** [comment]
vue.esm.js:3824 TypeError: Cannot read properties of undefined (reading 'scroll')
    at EventUtils.bind (tinymce.js:3277:41)
    at Proxy.eval (tinymce.js:4949:17)
    at each$4 (tinymce.js:4554:26)
    at init.each (tinymce.js:4945:16)
    at init.on (tinymce.js:4948:21)
    at toggleGlobalEvents (tinymce.js:28070:28)
    at Object.add (tinymce.js:28355:9)
    at render (tinymce.js:26097:28)
    at Editor.render (tinymce.js:27724:9)
    at createEditor (tinymce.js:28282:20)


to same to me.
