### ISSUE TITLE
tinymce fontFamily.replace is not a function  

### ISSUE THREAD

**Issue by paulwangtao** [tinymce/tinymce#8680]
5094:1 Uncaught SyntaxError: Illegal return statement
    at normalizeFontFamily (theme.js:14121:7)
    at Object.getFontFamily (theme.js:931:16)
    at Editor.<anonymous> (theme.js:14193:37)
    at Dispatcher.fire (tinymce.js:31557:31)
    at Editor.fire (tinymce.js:31797:41)
    at Object.nodeChanged (tinymce.js:35459:18)
    at Editor.nodeChanged (tinymce.js:40240:36)
    at Editor.<anonymous> (tinymce.js:37058:18)
    at Dispatcher.fire (tinymce.js:31557:31)
    at Editor.fire (tinymce.js:31797:41)

because fontFamily is : ( not font string )
init [body#tinymce.mce-content-body, context: body#tinymce.mce-content-body]
      return typeof fontFamily =='string'?fontFamily.replace(/[\'\"]/g, '').replace(/,\s+/g, ','):'';

**Comment by paulwangtao** [comment]
modify :
var normalizeFontFamily = function (fontFamily) {
// 'Font name', Font -> Font name,Font
return typeof fontFamily =='string'?fontFamily.replace(/['"]/g, '').replace(/,\s+/g, ','):'';
