### ISSUE TITLE
React "TestCafe" tests are failing with "TypeError: Illegal invocation" when working with tinyMCE  

### ISSUE THREAD

**Issue by alonzrihan** [tinymce/tinymce#8972]
**What is the current behavior? Describe the bug**
Preview:
We are using the self-hosted tinymce-react component.

When running test with "TestCafe" framework, the test starts to run as expected but when there is a reload/rerender of the page the test fails after a few seconds with the following message:

   JavaScript error details:
   TypeError: Illegal invocation
       at r._removeInternalProperties (hammerhead.js:16:7987)
       at r.dispose (hammerhead.js:16:8216)
       at t.eval (hammerhead.js:16:7750)
       at e.emit (hammerhead.js:4:8361)
       at t._emitEvent (hammerhead.js:15:5580)
       at t.handleEvent (hammerhead.js:15:8023)
       at t._removeNodeCore (http://10.1.28.12:50238/hammerhead.js:10:31534)
       at HTMLDivElement.removeChild (http://10.1.28.12:50238/hammerhead.js:11:2482)
       at Po ([path to tinymce package]/tinymce/themes/silver/theme.min.js:5:15425)
       at Vd ([path to tinymce package]/tinymce/themes/silver/theme.min.js:5:63038)

When adding the flag `skipJsErrors = true` to the test cafe config the tests are running as expected but we don't want to use it, for obvious reasons.

It is important to note that this issue happens on every page that includes the tinyMCE component, even without using it.

**Please provide the steps to reproduce and if possible, a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
run simple test with testcafe which include a self-hosted version of tinymce, during the test reload the page and try to click/change text

**What is the expected behavior?**
Not throwing this error and continue to run the test, as it does when the flag `skipJsErrors = true` is added 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
 "@tinymce/tinymce-react": "^4.3.0",
"tinymce": "^6.3.1",
"testcafe": "^1.20.1",

**Comment by alonzrihan** [comment]
the issue is in testcafe, fix can be found here
https://github.com/DevExpress/testcafe/issues/7943
