### ISSUE TITLE
Error for some users in pagebreak plugin

### ISSUE THREAD

**Issue by Burgov** [tinymce/tinymce#9074]
**What is the current behavior? Describe the bug**

Interestingly, out of hundreds of users, only 2 seem to be affected by this bug. When the TinyMCE editor opens up, this error is thrown:

```
TypeError: e.selection.isEditable is not a function
  at t(/tiny_mce/plugins/pagebreak/plugin.min.js:4:414)
  at Object.onSetup(/tiny_mce/plugins/pagebreak/plugin.min.js:4:457)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:122484)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:122436)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:122468)
  at run(/tiny_mce/themes/silver/theme.min.js:4:26247)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:30894)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:782)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:150497)
  at M.fold(/tiny_mce/themes/silver/theme.min.js:4:1075)
  at vw(/tiny_mce/themes/silver/theme.min.js:4:150405)
  at yw(/tiny_mce/themes/silver/theme.min.js:4:150797)
  at xw(/tiny_mce/themes/silver/theme.min.js:4:150884)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:152645)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:38048)
  at mi(/tiny_mce/themes/silver/theme.min.js:4:38812)
  at Object.triggerEvent(/tiny_mce/themes/silver/theme.min.js:4:152634)
  at Es(/tiny_mce/themes/silver/theme.min.js:4:25894)
  at Cs(/tiny_mce/themes/silver/theme.min.js:4:25739)
  at pd(/tiny_mce/themes/silver/theme.min.js:4:60176)
  at L(/tiny_mce/themes/silver/theme.min.js:4:2455)
  at pd(/tiny_mce/themes/silver/theme.min.js:4:60168)
  at hd(/tiny_mce/themes/silver/theme.min.js:4:60242)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:83878)
  at L(/tiny_mce/themes/silver/theme.min.js:4:2455)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:83862)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:83909)
  at Ol(/tiny_mce/themes/silver/theme.min.js:4:43891)
  at Mp(/tiny_mce/themes/silver/theme.min.js:4:83643)
  at set(/tiny_mce/themes/silver/theme.min.js:4:84641)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:42127)
  at M.fold(/tiny_mce/themes/silver/theme.min.js:4:1075)
  at Object.set(/tiny_mce/themes/silver/theme.min.js:4:41969)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:224119)
  at M.fold(/tiny_mce/themes/silver/theme.min.js:4:1075)
  at Object.setGroups(/tiny_mce/themes/silver/theme.min.js:4:223880)
  at setGroups(/tiny_mce/themes/silver/theme.min.js:4:224207)
  at Object.setGroups(/tiny_mce/themes/silver/theme.min.js:4:28905)
  at fE(/tiny_mce/themes/silver/theme.min.js:4:239890)
  at bE(/tiny_mce/themes/silver/theme.min.js:4:240172)
  at BE(/tiny_mce/themes/silver/theme.min.js:4:244003)
  at Object.setGroups(/tiny_mce/themes/silver/theme.min.js:4:244835)
  at ? (/tiny_mce/themes/silver/theme.min.js:4:256271)
  at M.each(/tiny_mce/themes/silver/theme.min.js:4:1767)
  at Object.setToolbar(/tiny_mce/themes/silver/theme.min.js:4:256233)
  at setToolbar(/tiny_mce/themes/silver/theme.min.js:4:258070)
  at Object.setToolbar(/tiny_mce/themes/silver/theme.min.js:4:28905)
  at gA(/tiny_mce/themes/silver/theme.min.js:4:276703)
  at jA.<anonymous>(/tiny_mce/themes/silver/theme.min.js:4:277088)
  at hA.dispatch(/tiny_mce/tinymce.min.js:4:372724)
```

Unfortunately, this only happens to them in the production environment, not in our dev environment, so I can't easily get them to trigger the error on the non-minified code. 

Naturally, I can't reproduce it myself.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Open the editor with the pagebreak plugin enabled.

**What is the expected behavior?**

The error is not thrown.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

We've upgraded from 6.4.2 to 6.7.0 a few weeks ago but this customer has only had this problem since yesterday. They tried a hard refresh.

**Comment by Burgov** [comment]
Interestingly, the problem was solved by clearing cookies...
