### ISSUE TITLE
TinyMCE and VITE: Cannot load skin.shadowdom.min.css and thus fails to show toolbar

### ISSUE THREAD

**Issue by 38leinaD** [tinymce/tinymce#9233]
## 📝 Provide detailed reproduction steps (if any)

I have followed the steps described [here](https://www.tiny.cloud/docs/tinymce/6/vite-es6-npm/) to use tinymce in a webcomponents project using Vite.

If you open [https://stackblitz.com/github/38leinaD/tinymce-vite-toolbar-issue](https://stackblitz.com/github/38leinaD/tinymce-vite-toolbar-issue) you can see that it fails to load some CSS files. It specifically seems to require some minified files: 
![image](https://github.com/tinymce/tinymce/assets/413413/b08c8f96-a51e-4784-91bc-333c16ecf4bc)

skin.shadowdom.min.css failure is causing it to not show the toolbar even.
Please note that for the toolbar to show it is not relevant to find any valid CSS, he just need to be able to fetch a file it seems. Because this issue only happens to me (which is deviating from the instructions in above linked steps) because i have appType: mpa in vite.config.js. If you switch to appType: spa, the toolbar shows. This is just because with spa, it will actually return the index.html content when requesting the css and it seems to make the toolbar happy.

### ✔️ Expected result
Should not have any errors on CSS files that cannot be loaded. Even more, it should show the toolbar.

### ❌ Actual result
Because it cannot load the skin.shadowdom.min.css, it also fails to show the editor toolbar.

Any guidance on how i could resolve it would be appreciated as I am not so familiar with Vite yet.

## 📃 Other details
- Browser: Chrome
- OS: Centos Linux
- First affected version: n/a
- Worked in version: n/a

**Comment by 38leinaD** [comment]
I am now starting to understand that the issue is related to the two things i left out because they seem to be not working anymore:

```
/* content UI CSS is required */
//import contentUiSkinCss from 'tinymce/skins/ui/oxide/content.js'; // Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/tinymce_skins_ui_oxide_content__js.js?v=ac513173' does not provide an export named 'default' (at editor.js:30:8)

/* The default content CSS can be changed or replaced with appropriate CSS for the editor content. */
//import contentCss from 'tinymce/skins/content/default/content.js'; // Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/tinymce_skins_content_default_content__js.js?v=61522085' does not provide an export named 'default' (at editor.js:33:8)

```

For the second statement, it seems that i can resolve it via doing

```
import 'tinymce/skins/content/default/content.js';
```
instead.

But not sure what to do about shadowdom.min.css as there is no corresponding js file called `skin.shadowdom.min.js`.
I can do
```
import 'tinymce/skins/ui/oxide/skin.shadowdom.js';
```
but he will then still not find the minified version.

Can i somehow tell the tinymce library to not look for the minified version but the skin.shadowdom.css instead?

**Comment by TheSpyder** [comment]
This process changed a bit with TinyMCE 6.8 when we added bundling for CSS files. You don't need a `.min.js`, the `.js` file will register itself such that no CSS is downloaded at all. Which means `import 'tinymce/skins/ui/oxide/skin.shadowdom.js';` should be correct.

We might have an issue in our docs. The bundled CSS should be imported in the same manner as the skins and icons, i.e. just `import 'tinymce/skins/ui/oxide/content.js';` without the `from` or the named variable.

I will pass this on to the engineers who implemented it and see whether our docs need to be fixed.

**Comment by TheSpyder** [comment]
I tried migrating your example (thank you for that!) to the code I expect and it still didn't work.

I tracked it down to a bug specifically in the `skin.shadowdom.css` loader. All the others are fine, but that one doesn't check for a bundled URL correctly.
https://github.com/tinymce/tinymce/blob/c19a0b94382ec10fbc518a832358c71f7dd9ded2/modules/tinymce/src/themes/silver/main/ts/ui/skin/Loader.ts#L42-L43

`skinUrl` in this case is the remote URL, not the local one added by `skin.shadowdom.js`.

I'm logging an internal bug, and it's an easy fix, but I think it's too late to squeeze into 6.8.2 (that's about to be published) and I don't know if we'll have time for a 6.8.3 before everyone breaks for the end of year holidays.

**Comment by 38leinaD** [comment]
Awesome. Thanks @TheSpyder ! Getting an official fix beginning of next year is absolutely fine for me. I have a hack/workaround to at least see the toolbar now. That should serve the purpose to continue implementing the application around the editor.
