### ISSUE TITLE
Missing .map files causes error when collecting the static files with Django's ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by philgyford** [tinymce/tinymce#9484]
## 📝 Provide detailed reproduction steps (if any)

1. Create a new Django project:
    ```shell
    python -m pip install django
    django-admin startproject myproject
    cd myproject
    mkdir static static_collected
    ```
2. Copy the downloaded `tinymce` directory into the `static` directory created above
3. Add these lines to the `myproject/myproject/settings.py` file:
    ```python
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }
    STATICFILES_DIRS = [ BASE_DIR / "static" ]
    STATIC_ROOT = BASE_DIR / 'static_collected'
    ```
4. Run the `collectstatic` command:
    ```shell
    ./manage.py collectstatic --noinput
    ```

### ✔️ Expected result

It should gather all the static files – including those in `static/tinymce/`–  into the `static_collected` directory.

### ❌ Actual result

A fatal error occurs.

```
$ ./manage.py collectstatic --noinput
Post-processing 'tinymce/js/tinymce/skins/ui/oxide/skin.shadowdom.js' failed!

Traceback (most recent call last):
  File "/Users/phil/Projects/personal/myproject/./manage.py", line 22, in <module>
    main()
  File "/Users/phil/Projects/personal/myproject/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 375, in _post_process
    content = pattern.sub(converter, content)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 249, in converter
    hashed_url = self._url(
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 425, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/Users/phil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 143, in hashed_name
    raise ValueError(
ValueError: The file 'tinymce/js/tinymce/skins/ui/oxide/skin.shadowdom.js.map' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x102be03a0>.
```

### ❓ Possible solution

The skins' `.js` files all end in lines like `//# sourceMappingURL=content.js.map`, referencing files that don't exist. If those files were added, or those lines removed, the error would not occur.

The lines were removed for previous versions thanks to issues such as #5489 and #4649, but they seem to have appeared again.

For the Django user, changing `ManifestStaticFilesStorage` to `StaticFilesStorage` fixes the issue, but this isn't an ideal solution for anyone already using the former.

## 📃 Other details
- Browser: n/a
- OS: n/a
- First affected version: `6.8.3 (2024-02-08)` (the only one I've tried)
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by philgyford** [comment]
FWIW there was a ticket filed on Django to let errors like this slide, but it was closed because third-party projects should either include the `.map` files, or else remove references to `.map` files that aren't included in the distribution: https://code.djangoproject.com/ticket/33353

**Comment by TheSpyder** [comment]
Ah the filter to remove the sourcemap was restricted to CSS files, and we added JS files in 6.8 without realising this was an issue. Apologies, I'll log a ticket to get this fixed.

**Comment by ziacik** [comment]
@TheSpyder any progress on this?

**Comment by TheSpyder** [comment]
@ziacik nothing yet, sorry. I've pinged the ticket to see if we can get it into a release soon.
