### ISSUE TITLE
When resizing the browser, the getCharacterCount method fails

### ISSUE THREAD

**Issue by jfduhamel** [tinymce/tinymce#9973]
ERROR TypeError: Cannot read properties of undefined (reading 'getBlockElements')
    at T (plugin.min.js:4:9777)
    at D (plugin.min.js:4:10195)
    at Object.getCharacterCount (plugin.min.js:4:10302)

## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. just resize the browser

### ✔️ Expected result
*What is the expected result of the above steps?*

### ❌ Actual result
*What is the actual result of the above steps?*

the getCharacterCount don't work anymore

## 📃 Other details
- Browser: chrome
- OS: macos
- version: 7.4.1

**Comment by lostkeys** [comment]
Hi @jfduhamel. I'm unable to replicate your issue. You need to provide a replication case.
